"""new

Revision ID: 4585d8e7ad59
Revises: cabe98a42373
Create Date: 2024-04-28 14:47:14.506697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4585d8e7ad59'
down_revision: Union[str, None] = 'cabe98a42373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('name', sa.String(), nullable=False))
    op.add_column('cards', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('cards', 'title')
    op.add_column('courses', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('courses', 'title')
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    op.add_column('courses', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('courses', 'name')
    op.add_column('cards', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('cards', 'active')
    op.drop_column('cards', 'name')
    # ### end Alembic commands ###
